const bookList = [
  {
    id: 1,
    name: "Spare",
    author: "Prince Harry",
    price: 50.0, // per-day rental price
    rentalPeriod: [
      { id: '1A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '1B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '1C', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 3,
    isAvailable: true,
    availableCopy: 3,
  },
  {
    id: 2,
    name: "Atomic Habits",
    author: "James Clear",
    price: 35.0,
    rentalPeriod: [
      { id: '2A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2D', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2E', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2F', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '2G', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 7,
    isAvailable: true,
    availableCopy: 7,
  },
  {
    id: 3,
    name: "It Starts with Us",
    author: "Colleen Hoover",
    price: 25.0,
    rentalPeriod: [
      { id: '3A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '3B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '3C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '3D', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '3E', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 5,
    isAvailable: true,
    availableCopy: 5,
  },
  {
    id: 4,
    name: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    price: 15.0,
    rentalPeriod: [
      { id: '4A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '4B', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 2,
    isAvailable: true,
    availableCopy: 2,
  },
  {
    id: 5,
    name: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    price: 40.0,
    rentalPeriod: [
      { id: '5A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5D', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5E', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5F', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5G', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '5H', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 8,
    isAvailable: true,
    availableCopy: 8,
  },
  {
    id: 6,
    name: "Dune",
    author: "Frank Herbert",
    price: 30.0,
    rentalPeriod: [
      { id: '6A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '6B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '6C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '6D', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 4,
    isAvailable: true,
    availableCopy: 4,
  },
  {
    id: 7,
    name: "The Book Thief",
    author: "Markus Zusak",
    price: 20.0,
    rentalPeriod: [
      { id: '7A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '7B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '7C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '7D', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '7E', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '7F', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 6,
    isAvailable: true,
    availableCopy: 6,
  },
  {
    id: 8,
    name: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 25.0,
    rentalPeriod: [
      { id: '8A', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 1,
    isAvailable: true,
    availableCopy: 1,
  },
  {
    id: 9,
    name: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 30.0,
    rentalPeriod: [
      { id: '9A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '9B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '9C', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 3,
    isAvailable: true,
    availableCopy: 3,
  },
  {
    id: 10,
    name: "The Silent Patient",
    author: "Alex Michaelides",
    price: 35.0,
    rentalPeriod: [
      { id: '10A', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10B', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10C', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10D', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10E', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10F', isRented: false, rentalPeriod: 0, rentedAt: null },
      { id: '10G', isRented: false, rentalPeriod: 0, rentedAt: null },
    ],
    totalCopy: 7,
    isAvailable: true,
    availableCopy: 7,
  }
];

export { bookList };
